## Curso de Manipulacion y Transformacion de Datos con Pandas y Numpy

## **Numpy Array**

In [1]:
import numpy as np 
import pandas as pd 

### **Array**
* La estructura central de Numpy 
* Representa datos de manera estructurada
* Indexado
* Acceso a uno o muchos elementos

In [2]:
lista = [0,1,2,3,4,5,6,7,8,9]
lista

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
arr = np.array(lista)
type(arr)

numpy.ndarray

In [4]:
matriz = ([1,2,3],[4,5,6],[7,8,9])
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
matriz [0,2]

3

In [6]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### **Slicing**

In [7]:
arr
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [8]:
arr = np.array(lista)
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4', b'5', b'6', b'7', b'8', b'9'],
      dtype='|S21')

### **Dimensiones**

In [9]:
# Definiendo un scalar
scalar = np.array(42)
print (scalar)
scalar.ndim

42


0

In [10]:
# Definiendo un vector
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [11]:
# Definiendo una matriz
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

### **Creando Arrays**

In [12]:
np.arange(0,20,1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
# Esto es util para crear array de iteracion o de imagenes con tamaños definidos
np.zeros((10,10))


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
# Linspace Hace una distribucion de los datos con un rango definido
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [17]:
# Return a 2-D array with ones on the diagonal and zeros elsewhere.
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.random.rand()

0.10152967416759406

In [19]:
np.random.rand(4)

array([0.17412306, 0.29346912, 0.32884215, 0.44083705])

In [20]:
np.random.rand(4,4)

array([[0.45091322, 0.45458381, 0.99031091, 0.64913539],
       [0.93025233, 0.59200663, 0.44864137, 0.96797475],
       [0.54421617, 0.63133235, 0.98009422, 0.30443858],
       [0.80320735, 0.9199267 , 0.08238732, 0.90903234]])

In [21]:
np.random.randint(1,15)

4

In [22]:
np.random.randint(1,100,(10,10))

array([[ 7, 11, 84, 11, 16, 54,  5, 28, 94, 28],
       [50, 32, 14, 18, 30, 20, 82, 57, 50, 65],
       [29, 11, 88, 78, 77, 24, 78, 45, 33, 47],
       [48, 95, 38, 26, 94, 63, 38, 73,  5, 39],
       [27,  9, 99, 90, 98, 87, 91, 78, 85, 66],
       [68, 38, 54, 76, 59, 68, 49, 80, 47, 31],
       [92, 27, 45, 83, 90, 15, 78, 82, 67, 70],
       [52, 45, 61, 22, 61, 48, 12, 52, 95, 24],
       [13, 57, 98, 22, 26, 21, 82, 36, 31, 18],
       [94, 72, 36, 43, 96, 36, 88, 98, 41, 94]])

### **Shape y Reshape**
Nos ayuda s identificar las caracteristicas de un arreglo y saber manipularlas

In [23]:
#Devuelve las dimensiones del arreglo
arr = np.random.randint(1,10,(3,2))
arr.shape 


(3, 2)

In [24]:
arr

array([[2, 4],
       [2, 6],
       [6, 9]])

In [25]:
# Cambia la forma del arreglo 
# Reshape, Gives a new shape to an array without changing its data.
arr.reshape(1,6)

array([[2, 4, 2, 6, 6, 9]])

In [26]:
arr.reshape(2,3)

array([[2, 4, 2],
       [6, 6, 9]])

In [27]:
np.reshape(arr,(1,6))

array([[2, 4, 2, 6, 6, 9]])

### **Funciones principales de Numpy**

In [28]:
arr = np.random.randint(1,20,10)
arr

array([ 1,  8,  8,  1,  3, 11,  6, 18, 17, 11])

In [29]:
matriz = arr.reshape(2,5)
matriz

array([[ 1,  8,  8,  1,  3],
       [11,  6, 18, 17, 11]])

In [30]:
# Devuelve el maximo valor en la matriz
matriz.max()

18

In [31]:
# Devuelve el valor maximo en una fila
matriz.max(1)

array([ 8, 18])

In [32]:
# Devuelve el indice del el valor maximo que se encuentra ubicado en el vector del array 
arr.argmax()

7

In [33]:
# Devuelve el valor minimo
arr.min()

1

In [34]:
# Pic to Pic, devuelve el valor entre los picos minimo y maximo del array 
arr.ptp()

17

In [35]:
# Retorna el valor que representa la mitad de los datos 
np.percentile(arr,50)

8.0

In [36]:
# Sort ordena el vector de menor a mayor
arr.sort()
arr

array([ 1,  1,  3,  6,  8,  8, 11, 11, 17, 18])

In [37]:
# Calcula la mediana de un numero especifico de datos 
np.median(arr)

8.0

In [38]:
# Calcula la desviacion estandar de un numero especifico de datos
np.std(arr)

5.6956123463592565

In [39]:
# Calcula la varianza de un numero especifico de datos
np.var(arr)

32.44

In [40]:
# Calcula el promedio de un numero especifico de datos 
np.mean(arr)

8.4

In [41]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])

In [42]:
a.ndim

2

In [43]:
b.ndim

1

In [44]:
b=np.expand_dims(b,axis=0)
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

###  Condiciones

In [45]:
arr = np.linspace(1,10,10, dtype="int8")
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [46]:
indices_cond = arr > 5


In [47]:
indices_cond 

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [48]:
arr[indices_cond]

array([ 6,  7,  8,  9, 10], dtype=int8)

### Operaciones 

In [49]:
lista = [1,2]
lista

[1, 2]