## Curso de Manipulacion y Transformacion de Datos con Pandas y Numpy

## **Numpy Array**

In [1]:
import numpy as np 
import pandas as pd 

### **Array**
* La estructura central de Numpy 
* Representa datos de manera estructurada
* Indexado
* Acceso a uno o muchos elementos

In [2]:
lista = [0,1,2,3,4,5,6,7,8,9]
lista

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
arr = np.array(lista)
type(arr)

numpy.ndarray

In [4]:
matriz = ([1,2,3],[4,5,6],[7,8,9])
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
matriz [0,2]

3

In [6]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### **Slicing**

In [7]:
arr
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [8]:
arr = np.array(lista)
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4', b'5', b'6', b'7', b'8', b'9'],
      dtype='|S21')

### **Dimensiones**

In [9]:
# Definiendo un scalar
scalar = np.array(42)
print (scalar)
scalar.ndim

42


0

In [10]:
# Definiendo un vector
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [11]:
# Definiendo una matriz
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

### **Creando Arrays**

In [12]:
np.arange(0,20,1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
# Esto es util para crear array de iteracion o de imagenes con tamaños definidos
np.zeros((10,10))


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
# Linspace Hace una distribucion de los datos con un rango definido
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [17]:
# Return a 2-D array with ones on the diagonal and zeros elsewhere.
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.random.rand()

0.3974690373052614

In [19]:
np.random.rand(4)

array([0.83689818, 0.35205424, 0.44967046, 0.40297113])

In [20]:
np.random.rand(4,4)

array([[0.37440454, 0.41508505, 0.06511929, 0.91858716],
       [0.88919991, 0.5792989 , 0.43673016, 0.28462195],
       [0.48092832, 0.25242116, 0.51808724, 0.168979  ],
       [0.62614179, 0.18898291, 0.24853644, 0.5973941 ]])

In [21]:
np.random.randint(1,15)

4

In [22]:
np.random.randint(1,100,(10,10))

array([[37, 23, 20, 26, 12, 58, 13, 37, 96, 99],
       [88,  5, 12, 49, 95, 21, 77, 56,  7, 21],
       [33, 20, 24, 23,  3, 86, 69, 99, 80, 71],
       [ 4, 78, 57, 33, 17,  2, 71, 58, 32, 34],
       [40, 29, 13, 92, 36, 43, 55, 54, 20, 58],
       [45, 16, 10, 58, 52, 36, 44, 33, 12, 31],
       [57,  7, 19, 24, 99, 14, 47, 37,  9, 96],
       [12, 71, 63, 54,  9, 83, 40, 40, 37, 14],
       [93, 38,  3, 67, 47, 81,  6,  3, 60, 70],
       [36,  3, 25, 25, 28, 79, 81, 76, 38, 65]])

### **Shape y Reshape**
Nos ayuda s identificar las caracteristicas de un arreglo y saber manipularlas

In [23]:
#Devuelve las dimensiones del arreglo
arr = np.random.randint(1,10,(3,2))
arr.shape 


(3, 2)

In [24]:
arr

array([[7, 5],
       [2, 6],
       [5, 1]])

In [25]:
# Cambia la forma del arreglo 
# Reshape, Gives a new shape to an array without changing its data.
arr.reshape(1,6)

array([[7, 5, 2, 6, 5, 1]])

In [26]:
arr.reshape(2,3)

array([[7, 5, 2],
       [6, 5, 1]])

In [27]:
np.reshape(arr,(1,6))

array([[7, 5, 2, 6, 5, 1]])

### **Funciones principales de Numpy**

In [28]:
arr = np.random.randint(1,20,10)
arr

array([ 5, 12, 14, 17,  4,  5,  6,  6, 17,  4])

In [29]:
matriz = arr.reshape(2,5)
matriz

array([[ 5, 12, 14, 17,  4],
       [ 5,  6,  6, 17,  4]])

In [30]:
# Devuelve el maximo valor en la matriz
matriz.max()

17

In [31]:
# Devuelve el valor maximo en una fila
matriz.max(1)

array([17, 17])

In [32]:
# Devuelve el indice del el valor maximo que se encuentra ubicado en el vector del array 
arr.argmax()

3

In [33]:
# Devuelve el valor minimo
arr.min()

4

In [34]:
# Pic to Pic, devuelve el valor entre los picos minimo y maximo del array 
arr.ptp()

13

In [35]:
# Retorna el valor que representa la mitad de los datos 
np.percentile(arr,50)

6.0

In [36]:
# Sort ordena el vector de menor a mayor
arr.sort()
arr

array([ 4,  4,  5,  5,  6,  6, 12, 14, 17, 17])

In [37]:
# Calcula la mediana de un numero especifico de datos 
np.median(arr)

6.0

In [38]:
# Calcula la desviacion estandar de un numero especifico de datos
np.std(arr)

5.118593556827891

In [39]:
# Calcula la varianza de un numero especifico de datos
np.var(arr)

26.2

In [40]:
# Calcula el promedio de un numero especifico de datos 
np.mean(arr)

9.0

In [41]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])

In [42]:
a.ndim

2

In [43]:
b.ndim

1

In [44]:
b=np.expand_dims(b,axis=0)
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])